### PR TITLE
Support React v16

### PR DESCRIPTION
**Pull request by avid21**
View.propTypes has been deprecated. Use ViewPropTypes instead.

### CODE REVIEW

**Comment by pinguinjkeke** [comment]
Hi!
Is ```style``` property supported by PropTypes library? It's React Native related property type.
```View.propTypes.style``` is not deprecated and working as we want.

**Comment by avid21** [comment]
@pinguinjkeke I corrected PR. `ViewPropTypes` is what we should use instead of `View.PropTypes`.

**Comment by pinguinjkeke** [comment]
Now it's okay

**Comment by avid21** [comment]
Thank you!

**Comment by pinguinjkeke** [comment]
@avid21 as I can see you opened PR #3 earlier and fixed falsy values behavior. Now it's completelty done 🤣

**Pull request merged**
